# Generated by Django 3.1.7 on 2021-04-08 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='date_of_birth',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
    ]
